#ifndef BLOCK_ART_H
#define BLOCK_ART_H

#include "gl.h"

// Generated by tools/gen_block_art.py (original art), 16x16, key 0xF81F.
extern const TEXTURE art_emerald_overlay;   // painted over the stone texture
extern const TEXTURE art_debris_side, art_debris_top;

// Paints the added blocks into free cells of the terrain atlas (row 4).
// Call before the resized and darkened copies of the atlas are made.
void paintAddedBlockTextures(TEXTURE &terrain, int field_width, int field_height);

#endif // BLOCK_ART_H
