#!/usr/bin/env python3
"""Draws the textures for blocks Crafti Survival Edition adds and writes block_art.cpp.

All art is original. Emerald ore is an overlay painted onto Crafti's own
stone texture at start-up, so it matches the other ores; Ancient Debris is a
full texture. Usage: python3 tools/gen_block_art.py (from the repository root).
"""
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_gui_art import Img, KEY, c_array  # noqa: E402


def emerald_overlay():
    # three small cut gems on a transparent background
    gem = [
        '.ohh.',
        'ohmmo',
        'ommso',
        '.oso.',
    ]
    pal = {'o': (8, 70, 30), 'h': (170, 255, 190), 'm': (40, 200, 90), 's': (16, 120, 50)}
    img = Img(16, 16)
    for gx, gy in ((2, 2), (9, 5), (4, 10), (11, 11)):
        for y, row in enumerate(gem):
            for x, ch in enumerate(row):
                if ch != '.':
                    img.set(gx + x, gy + y, pal[ch])
    return img


def debris_side():
    rnd = random.Random(33)
    img = Img(16, 16)
    for y in range(16):
        for x in range(16):
            base = (74, 52, 46)
            # dark curved bands, like layers of old scorched metal
            band = (x * 3 + (y - 8) ** 2 // 3) % 7
            if band in (0, 1):
                base = (40, 27, 24)
            if band == 3:
                base = (118, 88, 72)
            v = rnd.randint(-8, 8)
            img.set(x, y, tuple(max(0, min(255, c + v)) for c in base))
    # a few bright flecks
    for _ in range(5):
        img.set(rnd.randint(1, 14), rnd.randint(1, 14), (150, 118, 96))
    return img


def debris_top():
    rnd = random.Random(34)
    img = Img(16, 16)
    for y in range(16):
        for x in range(16):
            dx, dy = x - 7.5, y - 7.5
            ring = int((dx * dx + dy * dy) ** 0.5) % 3
            base = (66, 46, 40) if ring else (96, 70, 60)
            v = rnd.randint(-6, 6)
            img.set(x, y, tuple(max(0, min(255, c + v)) for c in base))
    return img


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    preview = os.path.join(root, 'tools', 'preview')
    os.makedirs(preview, exist_ok=True)
    out = ['// Generated by tools/gen_block_art.py - do not edit by hand.',
           '// All art is original to Crafti Survival Edition.',
           '#include "block_art.h"', '']
    for name, img in (('art_emerald_overlay', emerald_overlay()), ('art_debris_side', debris_side()),
                      ('art_debris_top', debris_top())):
        out.append(c_array(name, img.to565()))
        out.append('const TEXTURE %s = { %d, %d, true, 0x%04X, %s_data };' % (name, img.w, img.h, KEY, name))
        out.append('')
        img.save_preview(os.path.join(preview, name + '.png'), scale=8)
    with open(os.path.join(root, 'block_art.cpp'), 'w') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
