# Generate anti-aliased 4bpp bitmap fonts for nspGL
from PIL import Image, ImageDraw, ImageFont
import sys
FONTS = [
  ("sans",  "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 10),
  ("bold",  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 10),
  ("mono",  "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 10),
  ("h1",    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 16),
  ("h2",    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 13),
  ("small", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 8),
  ("ital",  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf", 10),
]
FIRST, LAST = 32, 255
out = ["/* generated by tools/genfont.py - DejaVu fonts (Bitstream Vera license) */", "#include <stdint.h>",
       "typedef struct { uint8_t adv, w, h; int8_t xo, yo; uint32_t off; } FGlyph;",
       "typedef struct { uint8_t height, ascent; const FGlyph *g; const uint8_t *bits; } FFont;"]
names = []
for name, path, size in FONTS:
    f = ImageFont.truetype(path, size)
    asc, desc = f.getmetrics()
    height = asc + desc
    bits = bytearray(); glyphs = []
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        if 127 <= cp < 160: ch = '?'
        adv = int(round(f.getlength(ch)))
        bbox = f.getbbox(ch)
        if bbox is None or bbox[2] <= bbox[0]:
            glyphs.append((adv, 0, 0, 0, 0, len(bits))); continue
        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=f, fill=255)
        px = list(img.getdata())
        off = len(bits)
        nib = [min(15, (p * 15 + 127) // 255) for p in px]
        if len(nib) % 2: nib.append(0)
        for i in range(0, len(nib), 2): bits.append(nib[i] | (nib[i + 1] << 4))
        glyphs.append((adv, w, h, x0, y0, off))
    out.append("static const uint8_t %s_bits[] = {%s};" % (name, ",".join(str(b) for b in bits) or "0"))
    out.append("static const FGlyph %s_g[] = {%s};" % (name, ",".join("{%d,%d,%d,%d,%d,%d}" % g for g in glyphs)))
    names.append((name, height, asc))
out.append("static const FFont g_fonts[] = {%s};" % ",".join("{%d,%d,%s_g,%s_bits}" % (h, a, n, n) for n, h, a in names))
out.append("enum { F_SANS, F_BOLD, F_MONO, F_H1, F_H2, F_SMALL, F_ITAL, F_COUNT };")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("ok", [(n, h, a) for n, h, a in names])
